# Generated by Django 5.1.1 on 2024-10-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_skill_item_experience_required_item_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='item',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
