# Generated by Django 5.1.1 on 2024-10-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_skills_delete_skill_item_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
