# Generated by Django 5.1.1 on 2024-10-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='job_type',
            field=models.CharField(choices=[('Linkedin', 'LinkedIn'), ('Naukri', 'Naukri'), ('CompanyWebsite', 'Website'), ('others', 'Others')], max_length=50),
        ),
    ]
