# Generated by Django 5.1.1 on 2024-11-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_rename_create_at_item_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
