# Generated by Django 5.1.1 on 2024-11-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_rename_created_at_item_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
    ]
