# Generated by Django 5.1.1 on 2024-11-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_remove_chatmessage_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uploaded_by',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('working_employee', 'Working Employee'), ('job_seeker', 'Job Seeker'), ('freelancer', 'Freelancer'), ('others', 'Others')], default='job_seeker', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='interview_type',
            field=models.CharField(choices=[('walkin', 'Walk-in'), ('reference', 'Reference'), ('online', 'Online'), ('offline', 'Offline'), ('others', 'Others')], max_length=50),
        ),
    ]
