# Generated by Django 5.1.1 on 2024-11-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_item_uploaded_by_alter_item_interview_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
